version: '2'
services:
    db:
      image: 'docker.io/mysql'
      container_name: 'mysql'
      labels:
        - "traefik.backend=mysql"
        - "traefik.frontend.rule=Host:mysql.localhost"
      networks: 
        - muidea-ai
      restart: always
      volumes:
        - /etc/localtime:/etc/localtime:ro
        - $PWD/mysql:/var/lib/mysql
      environment:
        MYSQL_ROOT_PASSWORD: rootkit
        TZ: "Asia/Shanghai"
      ports:
        - 3406:3306

    adminer:
      image: 'docker.io/adminer'
      container_name: 'adminer'
      labels:
        - "traefik.backend=adminer"
        - "traefik.frontend.rule=Host:adminer.localhost"
      networks: 
        - muidea-ai
      restart: always
      volumes:
        - /etc/localtime:/etc/localtime:ro
      environment:
        TZ: "Asia/Shanghai"

    magiccenter:
      image: 'muidea.ai/develop/magiccenter'
      container_name: 'magiccenter'
      labels:
        - "traefik.backend=magiccenter"
        - "traefik.frontend.rule=Host:magiccenter.localhost"
      networks: 
        - muidea-ai
      restart: always
      volumes:
        - /etc/localtime:/etc/localtime:ro
      environment:
        TZ: "Asia/Shanghai"
        LISTENPORT: "8080"
        DBSERVER: "db:3306"
        DBNAME: "magiccenter_db"
        ACCOUNT: "root"
        PASSWORD: "rootkit"

    magicsite:
      image: 'muidea.ai/develop/magicsite'
      container_name: 'magicsite'
      labels:
        - "traefik.backend=magicsite"
        - "traefik.frontend.rule=Host:magicsite.localhost"
      networks: 
        - muidea-ai
      restart: always
      volumes:
        - /etc/localtime:/etc/localtime:ro
      environment:
        TZ: "Asia/Shanghai"

    magicblog:
      image: 'muidea.ai/develop/magicblog'
      container_name: 'magicblog'
      labels:
        - "traefik.backend=magicblog"
        - "traefik.frontend.rule=Host:magicblog.localhost"
      networks: 
        - muidea-ai
      restart: always
      volumes:
        - /etc/localtime:/etc/localtime:ro
      environment:
        TZ: "Asia/Shanghai"
        LISTENPORT: "8080"
        CENTER_SERVER: "http://magiccenter:8080"
        NAME: "magicBlog"
        ENDPOINTID: "f0e078a8-6de8-4273-88a4-dccef60ff88f"
        AUTHTOKEN: "yTtWiuuoGifPVfcK5Mf4mdu8mGl78E3y"

    magicblogui:
      image: 'muidea.ai/develop/magicblogui'
      container_name: 'magicblogui'
      labels:
        - "traefik.backend=ui"
        - "traefik.frontend.rule=Host:ui.localhost"
      networks: 
        - muidea-ai
      restart: always
      volumes:
        - /etc/localtime:/etc/localtime:ro
      environment:
        TZ: "Asia/Shanghai"

    traefik:
      image: 'docker.io/traefik'
      command: --web --docker --docker.domain=localhost --logLevel=DEBUG
      container_name: 'traefik'
      labels:
        - "traefik.backend=traefik"
        - "traefik.frontend.rule=Host:traefik.localhost"
      networks:
        - muidea-ai
      restart: always
      volumes:
        - /etc/localtime:/etc/localtime:ro
        - /var/run/docker.sock:/var/run/docker.sock
        - $PWD/traefik:/etc/traefik
      environment:
        TZ: "Asia/Shanghai"
      ports:
        - 8080:8080
        - 80:80

networks:
  muidea-ai:
    driver: bridge
 
