version: '2'
services:
    db:
      image: 'docker.io/mysql'
      container_name: 'mysql'
      networks: 
        - muidea-ai
      restart: always
      volumes:
        - /etc/localtime:/etc/localtime:ro
        - $PWD/mysql:/var/lib/mysql
      environment:
        MYSQL_ROOT_PASSWORD: rootkit
        TZ: "Asia/Shanghai"
      ports:
        - 3406:3306

    adminer:
      image: 'docker.io/adminer'
      container_name: 'adminer'
      networks: 
        - muidea-ai
      restart: always
      volumes:
        - /etc/localtime:/etc/localtime:ro
      environment:
        TZ: "Asia/Shanghai"

    traefik:
      image: 'docker.io/traefik'
      command: --web --docker --docker.domain=localhost --logLevel=DEBUG
      container_name: 'traefik'
      networks:
        - muidea-ai
      restart: always
      volumes:
        - /etc/localtime:/etc/localtime:ro
        - /var/run/docker.sock:/var/run/docker.sock
        - $PWD/traefik/traefik.toml:/etc/traefik/traefik.toml        
      environment:
        TZ: "Asia/Shanghai"
      ports:
        - 8080:8080
        - 82:80

networks:
  muidea-ai:
 
